spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ride-sharing-driver
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: driver-service-group
      properties:
        spring.json.value.default.type: com.example.user_service.kafka.events.RideRequestEvent
        spring.json.trusted.packages: "*"
  redis:
    host: 172.17.0.2
    port: 6379



server:
  port: 8085



kafka:
  topic:
    location-events: location-events



logging:
  level:
    org.springframework: INFO
